telegram:
  bot:
    username: OpenAIProxyPyshBot
    token: ${BOT_TOKEN}

open-router:
  api-key: ${API_KEY}
  provisioning-key: ${PROVISIONING_KEY}

management:
  endpoints:
    web:
      exposure:
        include: refresh
